import { Truck } from 'lucide-react';
import PolicyPage from './PolicyPage';

export default function ShippingView() {
  return (
    <PolicyPage
      title="Shipping & Delivery Policy"
      subtitle="Carefully packaged to protect botanical active ingredients"
      badge="Last Updated: 26/07/2026"
      icon={<Truck className="h-5 w-5 text-secondary shrink-0" />}
      intro={[
        'At Aranya Organic, we are committed to ensuring that your orders are packed with care and delivered as efficiently as possible. This Shipping & Delivery Policy outlines the terms governing the shipment and delivery of products purchased from Aranya Organic.',
      ]}
      sections={[
        {
          title: '1. Order Processing',
          paragraphs: ['All orders are subject to verification, acceptance, and product availability. Orders are generally processed within 1-2 business days after payment confirmation and receipt of all necessary order details.', 'Orders placed on weekends, public holidays, or non-working days may be processed on the next business day. Aranya Organic reserves the right to delay processing where additional verification is required.'],
        },
        {
          title: '2. Delivery Timelines',
          paragraphs: ['Delivery timelines are estimates only and should not be considered guaranteed delivery dates. Most orders are delivered within 3-10 business days after dispatch, depending on delivery location and courier availability.', 'Delivery timelines may vary due to remote delivery locations, courier partner delays, weather conditions, public holidays, high order volumes, government restrictions, or events beyond our reasonable control. Aranya Organic shall not be liable for delays caused by such circumstances.'],
        },
        {
          title: '3. Shipping Charges',
          paragraphs: ['Shipping charges, if applicable, will be communicated at the time of order confirmation. Aranya Organic reserves the right to revise shipping charges at any time without prior notice. Any applicable shipping fees shall be displayed or communicated before the order is finalised.'],
        },
        {
          title: '4. Delivery Address Responsibility',
          paragraphs: ['Customers are responsible for providing accurate and complete delivery information. Aranya Organic shall not be responsible for delays, failed deliveries, additional shipping charges, or loss arising from incorrect addresses, incomplete addresses, incorrect contact information, or customer unavailability at the time of delivery.', 'If an order is returned due to incorrect delivery information, additional shipping charges may apply for re-dispatch.'],
        },
        {
          title: '5. Order Tracking',
          paragraphs: ['Where tracking services are available, tracking details may be provided once the order has been dispatched. Tracking updates are generated by courier partners and may not always reflect real-time shipment movement.'],
        },
        {
          title: '6. Multiple Shipments',
          paragraphs: ['In certain situations, products from the same order may be shipped separately due to product availability, packaging requirements, operational considerations, or courier limitations. No additional shipping charges will be applied solely because an order is shipped in multiple consignments.'],
        },
        {
          title: '7. Failed Delivery Attempts',
          paragraphs: ['Courier partners may attempt delivery multiple times depending on their policies. If delivery cannot be completed due to customer unavailability, refusal to accept delivery, or incorrect address information, the shipment may be returned to Aranya Organic. Any re-shipment costs may be borne by the customer.'],
        },
        {
          title: '8. Damaged Shipments',
          paragraphs: ['Customers are requested to inspect packages upon delivery. If a package appears visibly damaged, tampered with, leaking, or opened, customers should take photographs immediately, notify Aranya Organic within 48 hours of delivery, and retain all original packaging materials.', 'Claims reported after the specified period may not be eligible for review.'],
        },
        {
          title: '9. Lost Shipments',
          paragraphs: ['If a shipment is confirmed by the courier partner as lost in transit, Aranya Organic may, at its discretion, arrange a replacement shipment subject to stock availability or issue a refund for the affected order. Investigation timelines may vary depending on courier partner procedures.'],
        },
        {
          title: '10. International Shipping',
          paragraphs: ['Currently, Aranya Organic primarily ships within India. Any international shipping requests shall be subject to separate approval, shipping costs, customs regulations, duties, taxes, and delivery timelines applicable to the destination country.', 'Customers shall be responsible for any customs duties, import taxes, or local charges imposed by authorities outside India.'],
        },
        {
          title: '11. Force Majeure',
          paragraphs: ['Aranya Organic shall not be liable for delays, interruptions, or failures in delivery arising from circumstances beyond its reasonable control, including natural disasters, floods, fires, earthquakes, epidemics or pandemics, government actions, labour disputes, transportation disruptions, internet or communication failures, and utility outages. Delivery obligations shall remain suspended for the duration of such events.'],
        },
        {
          title: '12. Right to Refuse Shipment',
          paragraphs: ['Aranya Organic reserves the right to refuse, hold, delay, or cancel shipment of any order where fraudulent activity is suspected, required information is incomplete, payment verification is unsuccessful, product availability changes unexpectedly, or shipping restrictions apply. In such cases, customers will be notified and, where applicable, refunded according to company policies.'],
        },
        {
          title: '13. Contact Us',
          paragraphs: ['For questions regarding shipping, contact Aranya Organic at aranyaorganic1@gmail.com, WhatsApp 9920308677 / 9930318387, Mumbai, Maharashtra, India. Rooted in nature, crafted for you.'],
        },
      ]}
    />
  );
}
